config:
  cluster:
    node_id: 0
    seed_servers: []

  redpanda:
    auto_create_topics_enabled: true
    enable_sasl: false

  kafka_api:
    - address: 0.0.0.0
      port: 9092

  advertised_kafka_api:
    - address: redpanda
      port: 9092

tls:
  enabled: false

external:
  enabled: false

console:
  enabled: true
  config:
    kafka:
      brokers:
        - redpanda:9092
    redpanda:
      adminApi:
        enabled: true
        urls:
          - http://redpanda:9644
