{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hapi-fhir.name" . }}-config
  labels:
    {{- include "hapi-fhir.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.data }}
    {{ $key }}: |
  {{ $value | indent 4 }}
  {{- end }}
  {{- end }}
